-- Supabase schema for the Join app.
-- Run this in the Supabase SQL editor for your project.

create table if not exists public."demoDB" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  email text not null,
  phone bigint not null default 0,
  auth_user_id uuid references auth.users(id) on delete set null,
  "loggedIn" boolean not null default false,
  password text not null default ''
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  title text not null,
  description text not null default '',
  category text not null default 'category-0',
  type text not null,
  "dueDate" date not null,
  due_date date not null,
  priority text not null default 'medium'
    check (priority in ('urgent', 'medium', 'low')),
  "assignedTo" bigint[] not null default '{}',
  "assignedToNames" text[] not null default '{}',
  subtasks jsonb not null default '[]'::jsonb,
  status text not null default 'todo'
    check (status in ('todo', 'inProgress', 'awaitFeedback', 'done'))
);

alter table public."demoDB"
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists name text not null default '',
  add column if not exists email text not null default '',
  add column if not exists phone bigint not null default 0,
  add column if not exists auth_user_id uuid references auth.users(id) on delete set null,
  add column if not exists "loggedIn" boolean not null default false,
  add column if not exists password text not null default '';

alter table public.tasks
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists title text not null default '',
  add column if not exists description text not null default '',
  add column if not exists category text not null default 'category-0',
  add column if not exists type text not null default '',
  add column if not exists "dueDate" date,
  add column if not exists due_date date,
  add column if not exists priority text not null default 'medium',
  add column if not exists "assignedTo" bigint[] not null default '{}',
  add column if not exists "assignedToNames" text[] not null default '{}',
  add column if not exists subtasks jsonb not null default '[]'::jsonb,
  add column if not exists status text not null default 'todo';

create index if not exists demoDB_name_idx on public."demoDB" (name);
create index if not exists demoDB_auth_user_id_idx on public."demoDB" (auth_user_id);
create unique index if not exists demoDB_auth_user_id_unique_idx
  on public."demoDB" (auth_user_id)
  where auth_user_id is not null;

create index if not exists tasks_status_idx on public.tasks (status);
create index if not exists tasks_due_date_idx on public.tasks (due_date);

alter table public."demoDB" enable row level security;
alter table public.tasks enable row level security;

drop policy if exists "join_public_access_demoDB" on public."demoDB";
create policy "join_public_access_demoDB"
  on public."demoDB"
  for all
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "join_public_access_tasks" on public.tasks;
create policy "join_public_access_tasks"
  on public.tasks
  for all
  to anon, authenticated
  using (true)
  with check (true);

grant usage on schema public to anon, authenticated;
grant all on table public."demoDB" to anon, authenticated;
grant all on table public.tasks to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

alter table public."demoDB" replica identity full;
alter table public.tasks replica identity full;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'demoDB'
    ) then
      alter publication supabase_realtime add table public."demoDB";
    end if;

    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'tasks'
    ) then
      alter publication supabase_realtime add table public.tasks;
    end if;
  end if;
end $$;
